# Generated by Django 3.1.7 on 2021-03-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='is_guest',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mainuser',
            name='is_super_admin',
            field=models.BooleanField(default=False),
        ),
    ]
